<?php

use CRM_Elections_ExtensionUtil as E;

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2018
 *
 * Generated from /var/www/civicrm530/sites/default/files/civicrm/ext/au.com.agileware.elections/xml/schema/CRM/Elections/ElectionResult.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:5e354fe3275a98f2ba5ca8ff3e1c3a6d)
 */

/**
 * Database access object for the ElectionResult entity.
 */
class CRM_Elections_DAO_ElectionResult extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_election_result';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique ElectionResult ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * Rank of a member for particular position.
   *
   * @var int unsigned
   */
  public $rank;

  /**
   * FK to ElectionPosition for which this result is added.
   *
   * @var int unsigned
   */
  public $election_position_id;

  /**
   * FK to ElectionNomination for which this rank is added.
   *
   * @var int unsigned
   */
  public $election_nomination_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_election_result';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'election_position_id', 'civicrm_election_position', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'election_nomination_id', 'civicrm_election_nomination', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique Election Result ID'),
          'required' => TRUE,
          'table_name' => 'civicrm_election_result',
          'entity' => 'ElectionResult',
          'bao' => 'CRM_Elections_DAO_ElectionResult',
          'localizable' => 0,
        ],
        'rank' => [
          'name' => 'rank',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Rank'),
          'description' => E::ts('Rank of a member for particular position.'),
          'import' => TRUE,
          'where' => 'civicrm_election_result.rank',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => TRUE,
          'table_name' => 'civicrm_election_result',
          'entity' => 'ElectionResult',
          'bao' => 'CRM_Elections_DAO_ElectionResult',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
        ],
        'election_position_id' => [
          'name' => 'election_position_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to ElectionPosition for which this result is added.'),
          'table_name' => 'civicrm_election_result',
          'entity' => 'ElectionResult',
          'bao' => 'CRM_Elections_DAO_ElectionResult',
          'localizable' => 0,
          'title' => 'Election Position',
          'FKClassName' => 'CRM_Elections_DAO_ElectionPosition',
        ],
        'election_nomination_id' => [
          'name' => 'election_nomination_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to ElectionNomination for which this rank is added.'),
          'table_name' => 'civicrm_election_result',
          'entity' => 'ElectionResult',
          'bao' => 'CRM_Elections_DAO_ElectionResult',
          'localizable' => 0,
          'title' => 'Election Nomination',
          'FKClassName' => 'CRM_Elections_DAO_ElectionNomination',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'election_result', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'election_result', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
