name: civix upgrade
on:
  push

jobs:
  civix-upgrade:
    uses: agileware/ci-workflows/civix-upgrade-template-final.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    inputs:
      EXTENSION_NAME: au.com.agileware.elections
