name: Push changes
on:
  push
jobs:
  change-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install civix and regenerate module
        run: |
          composer global config minimum-stability dev
          composer global config --no-plugins allow-plugins.civicrm/composer-downloads-plugin true
          composer global config --no-plugins allow-plugins.civicrm/composer-compile-plugin true
          composer global require civicrm/civix
          civix generate:module
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[AUTO-COMMIT] civix regenerated"
      - name: Create pull request
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: "**Automated pull request** - civix regenerated"
          title: ${{ github.event.commits[0].message }}
